<?php if (isset($_SESSION['subscribe_hack'])) : ?>
<img src="http://atmail.com/newsletter_submit.php?&List=AO&Email=<?php echo $_SESSION['pref']['admin_email'] ?>" style="display:hidden" />
<?php endif; ?>

<h2>Installation Complete</h2>
<p>The Atmail WebMail Client is now configured and ready to use.</p>

<?php if($var['htaccess_error']): ?>
<div class="error">
<h3>Warning</h3>
<p>A .htaccess file could not be created in
<code><?php echo $var['install_dir'] ?>/install/</code>. To prevent further access to the installer you will
need to create a file called <code>.htaccess</code> in <code><?php echo $var['install_dir'] ?>/install/</code>
and place the following in it:</p>

<p><code><pre>
&lt;FilesMatch "\.(php|html)$"&gt;
order allow,deny
deny from all
&lt;/Files&gt;
</pre></code></p>

<p>Alternatively you may wish to archive, move or otherwise make the install directory unavailable
to the webserver.</p>
</div>
<?php endif; ?>

<?php if ($var['missing_ext']): 
echo $var['missing_ext']; 
endif; ?>

<?php if($var['rename_error']): ?>
<div class="error">
<h3>Warning</h3>
<p>Could not rename <code><?php echo $var['install_dir'] ?>/_index.php</code> to
<code><?php echo $var['install_dir'] ?>/index.php</code>. Please do this manually so your login page can be accessed.</p>
</div>
<?php endif; ?>

<?php if(!$var['htaccess_error']): ?>
<p>Please note that a .htaccess file was created in the <code><?php echo $var['install_dir'] ?>/install</code> directory
to prevent a malicous re-installation. If for some reason you wish to re-run the installer
you will need to delete this file.</p>
<?php endif; ?>

<p><input type="button" value="Login to Webmail" onClick="document.location='<?php echo $var['login_url'] ?>/'"></p>
<p><strong>Thank you for choosing Atmail!</strong></p>
